# Generated by Django 5.1.5 on 2025-01-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("email", models.CharField(max_length=122)),
                ("phno", models.IntegerField(max_length=12)),
                ("desc", models.TextField()),
                ("city", models.CharField(max_length=30)),
                ("zipcode", models.IntegerField(max_length=8)),
            ],
        ),
    ]
