# Generated by Django 5.1.5 on 2025-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phno",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="zipcode",
            field=models.IntegerField(),
        ),
    ]
